### ISSUE TITLE
MCH test database: wind speed and direction

### ISSUE THREAD

**Issue by isedwards** [opencdms/process#2]
In the short term, we need an example of wind speed and wind direction data in a format similar to how it is stored in the MCH database.

Ideally, we would also have the SQL commands to:
a) `create` the minimal set of required table(s) and `insert` the test data
b) `select` the wind speed and wind direction data

Overtime, we will build up the test database to include related metadata.
See also #1, #3

**Comment by isedwards** [comment]
I'm looking forward to seeing this example of wind speed and wind direction data as they are stored in an MCH database.

As far as I can see, [Create_MCH_English_basic_tables.sql](https://github.com/opencdms/datamodel/blob/master/mch/Create_MCH_English_basic_tables.sql) doesn't contain any tables for storing observations, therefore two new tables will be created: one for wind speed and one for wind direction.

Do you have information on all of the other tables that are usually created in order to store observations for other elements?

**Comment by jaggh** [comment]
Here is an example of wind rose from MCH plus the minimal set of tables needed. I hope it helps.
[mch_windrose.zip](https://github.com/opencdms/process/files/5017505/mch_windrose.zip)
[mysql_tables.zip](https://github.com/opencdms/process/files/5017506/mysql_tables.zip)

**Comment by isedwards** [comment]
Thank you @jaggh. Quick question: The data in `mysql_tables.zip` is in MyISAM format
- Would it be easy to export (dump) the example tables as a single SQL file?
- Are there any features specific to the [MyISAM storage engine](https://en.wikipedia.org/wiki/MyISAM) that you are relying on?

**Comment by jaggh** [comment]
Sorry Ian, I am not an expert in databases. This is the required way for MCH, and I just exported the wind data of one station during one month, replaced those tables with empty ones, and imported the data into them to provide the minimum amount of data for the example. Export and import operations were done within MCH, so no SQL code was needed from my side...

**Comment by isedwards** [comment]
Thank you Jose - these conversations are really good - we are getting a better understanding of how everything works in different solutions. I believe I would probably have to install an older version of MySQL to [import the table files](https://stackoverflow.com/questions/53834718/import-table-frm-table-myd-and-table-myi) easily.

Is this the main way in which an MCH database is backed up? Being able to import MCH MyISAM backups may be an important use case to consider.

**Comment by jaggh** [comment]
I am sorry about the extra work. Please, tell me if I can run any specific SQL to produce a more manageable file containing the same data.
Etna and Eduardo are who can give more details about the way MCH deals with MySQL. What I was told is that making a backup is as simple as copying the database directory. (Having stopped the mysql service, I guess...)

**Comment by isedwards** [comment]
Extra work is a good thing. It's important that we're able to support capabilities that users regularly need or at least be aware of the tyoes of situation that may arise. A future use case could be something like: Restore an MCH backup to a Climsoft database.

(Actually, restoring a Climsoft SQL backup to another system would also not be trivial...)

You should be able to get an SQL dump of the `dtwinddirn`, `dtwindspeed` and `stations` tables from the linux command line with:

```
mysqldump -u username -p mch_database_name dtwinddirn dtwindspeed stations > mch_windrose.sql

```
(replacing `username` and `mch_database_name` above accordingly).

If you're not sure of the MCH database name then it may be possible to find it from the mysql command line client: ```mysql -u username -p```

Trying typing: ```SHOW DATABASES```

If this doesn't work we'll need help from @githubetna and @eporrasc

**Comment by jaggh** [comment]
Thank you, Ian. Attached is the zipped SQL file.
[mch_windrose_sql.zip](https://github.com/opencdms/process/files/5023048/mch_windrose_sql.zip)

**Comment by jaggh** [comment]
Here is the updated Climatol windrose function, using a data frame as input and calculating the wind frequencies in 16 directions (this number could be parameterized in the future, but it is quite a standard...)
[windrose.zip](https://github.com/opencdms/process/files/5046014/windrose.zip)

**Comment by eporrasc** [comment]
Hello,

This is a dump of the wind speed and wind direction tables, the MCH database is MyIsam.
[windspeed and direction.zip](https://github.com/opencdms/process/files/5130074/windspeed.and.direction.zip)

**Comment by isedwards** [comment]
This issue has been replaced by #10
