### ISSUE TITLE
In RInstatClimatic Python layer, support data frames that contain date/time fields without timezone information?

### ISSUE THREAD

**Issue by lloyddewit** [opencdms/process#30]
PR #29 adds a Python layer for the [RInstatClimatic R package](https://github.com/IDEMSInternational/cdms.products). 
The Python layer:

- interacts with the R library using the Rpy2 package
- accepts Python Pandas data frames
- converts these Pandas data frames to R data frames using the rpy2 `conversion.py2rpy()` function

Currently, any date/time fields in the data frame must contain time zone information, e.g. `1945-01-01T00:00:00Z`. If the time zone is not specified, then `py2rpy()` will assume that the date/time is in the system’s default timezone, and will convert the time to UTC.

For example, if the date/time is specified without timezone (e.g. `1945-01-01`), and the system's timezone is GMT+1, then `py2rpy()` will convert `1945-01-01` to `1944-12-31T23:00:00Z`.

**Should the Python layer also accept date/time fields without a timezone specified?
If yes, then should we assume the date/time field's timezone is UTC?**

Note: The relevent Rpy2 documentation can be found [here](https://rpy2.github.io/doc/v3.4.x/html/pandas.html). It states:

> The timezone used for conversion is the system’s default timezone unless pandas2ri.default_timezone is specified… or unless the time zone is specified in the original time object. 

However, it does not specify how to change `default_timezone`. It may be possible to deduce this from the source code. The source code can be found [here](https://github.com/rpy2/rpy2). This [issue](https://github.com/rpy2/rpy2/issues/634) may also be relevent.

**Comment by dannyparsons** [comment]
Thanks for finding this issue. You get similar kinds of problems in R with timezones and it can really mess things up.

I think we don't want to rely on using the systems timezone as that means the same data will be processed differently on different machines.

For many applications e.g. daily, 10-day, monthly, annual data, the time component of the date-time is not needed for the analysis and it shouldn't be expected that date-time given as `1945-01-01` should need to specify a timezone. So I think YES to your first question on accepting date-times without a timezone.

And YES I think it is sensible to assume UTC time if no timezone is provided. I think we want a simple rule that will mean values don't get changed artificially. I think the default being UTC would do this?

So ideally I think we set the default timezone in Rpy2. This commit might be helpful in doing that? https://github.com/rpy2/rpy2/commit/39a152fe20bdd690bcbd6303a844d46329c6042f

Is it accessible at `rpy2.robjects.pandas2ri.default_timezone`?

This could then be a simple installation setting and if for some reason an installation in a particular place wanted to have a different default time zone that could be set through this setting.

**Comment by lloyddewit** [comment]
@dannyparsons Thank you, I agree that we should accept date/time fields without timezone information, and we should assume that these date/time fields are UTC.

I looked at the rpy2 source code. I think that there is an error in the rpy2 documentation, and I could not see a way to specify that date/times without timezone information should be treated as UTC. I raised an issue in their GitHub repo. Rpy2 is still being actively maintained but I don't know if/when they will respond.

In the meantime as a workaround, I'll look at ways to add UTC time zone information to the Pandas data frame, before it is converted to an R data frame.

**Comment by lloyddewit** [comment]
@dannyparsons Thanks also for your extra suggestions ...

> So ideally I think we set the default timezone in Rpy2. This commit might be helpful in doing that? https://github.com/rpy2/rpy2/commit/39a152fe20bdd690bcbd6303a844d46329c6042f

This commit was relevent but since then the code has changed again and these changes have been removed.

> Is it accessible at rpy2.robjects.pandas2ri.default_timezone?

Unfortunatley not, this attribute no longer exists.

**Comment by lloyddewit** [comment]
Fixed in PR #29
